// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axwtqezfybvpmppnevtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4d3RxZXpmeWJ2cG1wcG5ldnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2Mjc5NzMsImV4cCI6MjA1NDIwMzk3M30._ThoE1e5WM2_gH7cSshkm66g5wFhRU5Yytwe5sWEt6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);